services:
  redis:
    image: redis:8
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "admin"]

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SenhaForte@123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: [
        "CMD-SHELL",
        "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P 'SenhaForte@123' -Q 'SELECT 1' || exit 1"
      ]
      interval: 10s
      timeout: 5s
      retries: 10
      
volumes:
  sqlserver_data: