@API_HostAddress = https://localhost:7146

# GET Authentication V1
GET {{API_HostAddress}}/api/v1/authentication
Accept: application/json

###

# GET Authentication V2
GET {{API_HostAddress}}/api/v2/authentication
Accept: application/json

###
